### ISSUE TITLE
Google TTS Error: Could not load the default credentials

### ISSUE THREAD

**Issue by shilik** [tegnike/aituber-kit#178]
@tegnike 

ご指示の通りにgoogle cloud でcredentials.jsonを生成し、aituber-kit に入れると、以下のようなエラーが出てきました。
` ⨯ Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/home/ilik/aituber-kit/node_modules/google-auth-library/build/src/auth/googleauth.js:292:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoogleAuth._GoogleAuth_determineClient (/home/ilik/aituber-kit/node_modules/google-auth-library/build/src/auth/googleauth.js:839:32)
    at async GoogleAuth.getClient (/home/ilik/aituber-kit/node_modules/google-auth-library/build/src/auth/googleauth.js:703:20)
    at async GrpcClient._getCredentials (/home/ilik/aituber-kit/node_modules/google-gax/build/src/grpc.js:145:24)
    at async GrpcClient.createStub (/home/ilik/aituber-kit/node_modules/google-gax/build/src/grpc.js:318:23) {
  page: '/api/tts'
}`

どうすればいいか、教えていただけないようでしょうか

**Comment by shilik** [comment]
` POST /api/difyChat/ 200 in 1745ms
 ⨯ Error: 3 INVALID_ARGUMENT: Voice 'ja-JP' does not exist. Is it misspelled?
    at callErrorFromStatus (/home/shilik/aituber-kit/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/home/shilik/aituber-kit/node_modules/@grpc/grpc-js/build/src/client.js:193:76)
    at Object.onReceiveStatus (/home/shilik/aituber-kit/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/home/shilik/aituber-kit/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /home/shilik/aituber-kit/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/shilik/aituber-kit/node_modules/@grpc/grpc-js/build/src/client.js:161:32)
    at ServiceClientImpl.<anonymous> (/home/shilik/aituber-kit/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /home/shilik/aituber-kit/node_modules/@google-cloud/text-to-speech/build/src/v1/text_to_speech_client.js:210:29
    at /home/shilik/aituber-kit/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/home/shilik/aituber-kit/node_modules/google-gax/build/src/normalCalls/retries.js:82:25)
    at /home/shilik/aituber-kit/node_modules/google-gax/build/src/normalCalls/retries.js:125:13
    at OngoingCallPromise.call (/home/shilik/aituber-kit/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/home/shilik/aituber-kit/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /home/shilik/aituber-kit/node_modules/google-gax/build/src/createApiCall.js:112:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 3,
  details: "Voice 'ja-JP' does not exist. Is it misspelled?",
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient',
  page: '/api/tts'
}
 POST /api/tts/ 500 in 179ms`

**Comment by tegnike** [comment]
すみません、こちらクローズされていますが解決されたということで問題ないでしょうか？

**Comment by shilik** [comment]
Issue分析結果に基づいて
認証情報のファイルパスを明示的に指定することによって
# .env
GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/credentials.json
GOOGLE_CLOUD_PROJECT=your-project-id
言語選択はstandardの種類を選択すれば、例えば　ja-JP-Standard-A
予想通りに音声が出てきます。

ところで
言語モデルは下記のURLから選択してください。
https://cloud.google.com/text-to-speech/docs/voices
上のURLを直接にクリックする代わりに、ブラウザーにコピペで言語モデルを見ることができます。
そうでなければ　Service Unavailable　になってしまいました。




https://cloud.google.com/text-to-speech/docs/voices

**Comment by tegnike** [comment]
理解しました。ご指摘ありがとうございます。

**Comment by shilik** [comment]
同じくTTSの問題ですが、Voicevoxをubuntu(AIVtuberも同じサーバー)にインストールしてから、サーバーのIPからhttp プロトコールでVoicevoxへ音声生成させようとしたら、ずっと拒否され、失敗しました。CORSにかかわっているのを知っていますが、VOICEVOX側の、CorsPolicyMode.allやallow_originにサーバーのIPを入れたりしてみましたが、全部ダメになりました。
以上のような問題は良い解決策があるのでしょうか。

**Comment by tegnike** [comment]
VOICEVOXは、デフォルトのURLのみしか許可していないので、直接コードを修正する必要があります。 

https://github.com/tegnike/aituber-kit/blob/3a78174e8ec7eee278f068a051c7eb8c0890d6bf/src/features/messages/speakCharacter.ts#L16

自前のVOICEVOXサーバーであってもパラメータ等は変わらないはずなので、ここを修正すれば疎通できるはずです。  
もし失敗してしまう場合は、AITuberKitからではなく直接curlなどでVOICEVOXから適切なレスポンスが返るか確認してみてください。

**Comment by shilik** [comment]
VOICE_VOX_API_URL内容の編集は結果がダメになってしまいました。
https://github.com/VOICEVOX/voicevox_engine/blob/master/README.md
からのHTTP リクエストで音声合成するサンプルコードを借りてipを変えて試しましたが、空っぽなファイルしか生成しなかったのです。

**Comment by tegnike** [comment]
すみません、ちょっと状況が理解できませんでした。
まず確認ですが、ご自身で用意したVOICEVOXサーバーにAITuberKit以外からリクエストした場合に適切なレスポンスは受け取れましたか？

**Comment by shilik** [comment]
> すみません、ちょっと状況が理解できませんでした。 まず確認ですが、ご自身で用意したVOICEVOXサーバーにAITuberKit以外からリクエストした場合に適切なレスポンスは受け取れましたか？

やはり全部拒否された結果となりました。これはおそらくvoicevoxのCORS設定による問題だと思います。
先週末までずっとCORSの問題に悩まされて、今うまく行っているのはGoogle TTSとElevenLabsのみです。
ちなみに、選択肢の項目名なんですが、"ElevenLabs"でなく、"Using ElevenLabs"は何か理由があるますか。

**Comment by tegnike** [comment]
なるほど、となるとVOICEVOXサーバーに問題がありそうですね。
その問題を解決したあとにAITuberKitでもトライしてみるとよいかと思います。

> "ElevenLabs"でなく、"Using ElevenLabs"は何か理由があるますか。

おっと気づきませんでした。直しておきます。
